// AUTO-GENERATED by scripts/genModuleParams.mjs — do not edit by hand.
// Re-run: npm run gen:module-params
import type { ModuleParam } from './moduleParams';

export const GENERATED_MODULE_PARAMS: Record<string, ModuleParam[]> = {
  "/amperes-law": [
    {"kind":"number","label":"Wire current","key":"wire-current","min":-20,"max":20,"step":0.1,"default":8,"units":"A"},
    {"kind":"number","label":"Amperian loop radius","key":"amperian-loop-radius","min":0.1,"max":0.9,"step":0.01,"default":0.45,"units":"m"},
    {"kind":"number","label":"Wire offset from center","key":"wire-offset-from-center","min":-0.9,"max":0.9,"step":0.01,"default":0.12,"units":"m"},
    {"kind":"number","label":"Relative permeability (μr)","key":"relative-permeability-r","min":0.5,"max":300,"step":0.5,"default":1},
  ],
  "/beam-balance": [
    {"kind":"number","label":"Left mass","key":"left-mass","min":0.2,"max":15,"step":0.1,"default":6,"units":"kg"},
    {"kind":"number","label":"Left distance","key":"left-distance","min":0.2,"max":2.5,"step":0.05,"default":1.2,"units":"m"},
    {"kind":"number","label":"Right mass","key":"right-mass","min":0.2,"max":15,"step":0.1,"default":4,"units":"kg"},
    {"kind":"number","label":"Right distance","key":"right-distance","min":0.2,"max":2.5,"step":0.05,"default":1.4,"units":"m"},
  ],
  "/bernoulli-flow-explorer": [
    {"kind":"number","label":"Entrance radius","key":"entrance-radius","min":0.1,"max":2,"step":0.05,"default":0.75,"units":"m"},
    {"kind":"number","label":"Exit radius","key":"exit-radius","min":0.1,"max":2,"step":0.05,"default":0.35,"units":"m"},
    {"kind":"number","label":"Entrance height","key":"entrance-height","min":-10,"max":10,"step":0.25,"default":2,"units":"m"},
    {"kind":"number","label":"Exit height","key":"exit-height","min":-10,"max":10,"step":0.25,"default":-1.5,"units":"m"},
    {"kind":"number","label":"Fluid density","key":"fluid-density","min":100,"max":2000,"step":50,"default":1000,"units":"kg/m³"},
  ],
  "/buoyancy-explorer": [
    {"kind":"number","label":"Object mass","key":"m","min":0.1,"max":1000,"step":0.1,"default":38,"units":"kg"},
    {"kind":"number","label":"Square side length","key":"l","min":0.1,"max":3,"step":0.05,"default":0.4,"units":"m"},
    {"kind":"number","label":"Gravity (g)","key":"g","min":0.1,"max":25,"step":0.1,"default":9.81,"units":"m/s²"},
  ],
  "/capacitor": [
    {"kind":"number","label":"Plate area","key":"plate-area","min":40,"max":500,"step":1,"default":180,"units":"cm²"},
    {"kind":"number","label":"Plate spacing","key":"plate-spacing","min":1.5,"max":15,"step":0.1,"default":5,"units":"mm"},
    {"kind":"number","label":"Dielectric constant","key":"dielectric-constant","min":1,"max":12,"step":0.1,"default":2.4,"units":"k"},
    {"kind":"number","label":"Voltage","key":"voltage","min":0,"max":80,"step":0.1,"default":24,"units":"V"},
    {"kind":"number","label":"Charge","key":"charge","min":0,"max":30,"step":0.1,"default":0,"units":"nC"},
  ],
  "/coulombs-law": [
    {"kind":"number","label":"Charge q1","key":"charge-q1","min":-10,"max":10,"step":0.1,"default":3,"units":"uC"},
    {"kind":"number","label":"Charge q2","key":"charge-q2","min":-10,"max":10,"step":0.1,"default":-4,"units":"uC"},
    {"kind":"number","label":"Separation r","key":"separation-r","min":0,"max":5,"step":0.1,"default":1.2,"units":"m"},
  ],
  "/energy-hills": [
    {"kind":"number","label":"Mass (m)","key":"m","min":0.5,"max":20,"step":0.5,"default":2,"units":"kg"},
    {"kind":"number","label":"Initial velocity (v₀)","key":"Vo","min":0,"max":20,"step":0.25,"default":2,"units":"m/s"},
  ],
  "/faradays-law": [
    {"kind":"number","label":"Magnet speed","key":"magnet-speed","min":0.2,"max":2.2,"step":0.05,"default":0.9,"units":"m/s"},
    {"kind":"number","label":"Peak magnetic field","key":"peak-magnetic-field","min":0.08,"max":0.7,"step":0.01,"default":0.32,"units":"T"},
    {"kind":"number","label":"Coil area","key":"coil-area","min":0.001,"max":0.012,"step":0.0005,"default":0.0055,"units":"m^2"},
    {"kind":"number","label":"Number of turns","key":"number-of-turns","min":20,"max":400,"step":5,"default":150,"units":"turns"},
    {"kind":"number","label":"Flux spread (sigma)","key":"flux-spread-sigma","min":0.12,"max":0.55,"step":0.01,"default":0.28,"units":"m"},
    {"kind":"number","label":"Sensor offset","key":"sensor-offset","min":-0.08,"max":0.08,"step":0.002,"default":0.012,"units":"V"},
    {"kind":"number","label":"Sensor noise","key":"sensor-noise","min":0,"max":0.08,"step":0.002,"default":0.02,"units":"V"},
  ],
  "/fluid-flow-explorer": [
    {"kind":"number","label":"Entrance radius","key":"entrance-radius","min":0.1,"max":2,"step":0.05,"default":0.75,"units":"m"},
    {"kind":"number","label":"Exit radius","key":"exit-radius","min":0.1,"max":2,"step":0.05,"default":0.35,"units":"m"},
    {"kind":"number","label":"Entrance velocity","key":"entrance-velocity","min":0.1,"max":20,"step":0.1,"default":2.5,"units":"m/s"},
  ],
  "/frequency-generator": [
    {"kind":"number","label":"Sine tone frequency","key":"freq","min":0,"max":5000,"step":1,"default":440,"units":"Hz"},
  ],
  "/gauss-law": [
    {"kind":"number","label":"Enclosed charge","key":"enclosed-charge","min":-20,"max":20,"step":0.1,"default":8,"units":"nC"},
    {"kind":"number","label":"Radius","key":"radius","min":0.2,"max":3,"step":0.05,"default":1.2,"units":"m"},
    {"kind":"number","label":"Cylinder height","key":"cylinder-height","min":0.4,"max":4,"step":0.05,"default":1.8,"units":"m"},
    {"kind":"number","label":"Cube length","key":"cube-length","min":0.3,"max":3,"step":0.05,"default":1.6,"units":"m"},
  ],
  "/gravity-friction": [
    {"kind":"number","label":"Rope pull force","key":"rope-force","min":0,"max":60,"step":0.5,"default":15,"units":"N"},
    {"kind":"number","label":"Mass","key":"mass","min":0.5,"max":20,"step":0.1,"default":5,"units":"kg"},
  ],
  "/ideal-gas-law-explorer": [
    {"kind":"number","label":"Temperature","key":"temperature","min":50,"max":1000,"step":5,"default":300,"units":"K"},
    {"kind":"number","label":"Number of moles","key":"number-of-moles","min":0.1,"max":10,"step":0.1,"default":1,"units":"mol"},
    {"kind":"number","label":"Container height (volume)","key":"container-height-volume","min":0.06,"max":0.68,"step":0.01,"default":0.35,"units":"m"},
  ],
  "/impulse-builder": [
    {"kind":"number","label":"Mass","key":"impulse-mass","min":0.5,"max":20,"step":0.1,"default":4,"units":"kg"},
    {"kind":"number","label":"Initial velocity","key":"impulse-v0","min":-10,"max":10,"step":0.1,"default":0,"units":"m/s"},
    {"kind":"number","label":"Force (+x only)","key":"impulse-force-mag","min":0,"max":50,"step":0.5,"default":20,"units":"N"},
    {"kind":"number","label":"Time force is applied","key":"impulse-duration","min":0,"max":5,"step":0.05,"default":1.5,"units":"s"},
  ],
  "/kinematics": [
    {"kind":"number","label":"Acceleration due to gravity","key":"acceleration-due-to-gravity","min":0,"max":25,"step":0.1,"default":9.8,"units":"m/s²"},
    {"kind":"number","label":"Initial velocity","key":"initial-velocity","min":-35,"max":35,"step":0.5,"default":0,"units":"m/s"},
    {"kind":"number","label":"Initial height","key":"initial-height","min":0,"max":30,"step":0.1,"default":10,"units":"m"},
  ],
  "/kinematics-2d": [
    {"kind":"number","label":"Acceleration (gravity)","key":"gravity","min":0,"max":25,"step":0.1,"default":9.8,"units":"m/s²"},
    {"kind":"number","label":"Initial height","key":"initial-height","min":0,"max":50,"step":0.1,"default":10,"units":"m"},
  ],
  "/mag-field": [
    {"kind":"number","label":"Field density","key":"field-density","min":16,"max":36,"step":1,"default":24},
  ],
  "/maxwell": [
    {"kind":"number","label":"Electric field peak","key":"ePeak","min":20,"max":1200,"step":1,"default":380,"units":"V/m"},
    {"kind":"number","label":"Frequency","key":"freq","min":1,"max":1200,"step":1,"default":95,"units":"MHz"},
    {"kind":"number","label":"Phase offset","key":"phase","min":-180,"max":180,"step":1,"default":0,"units":"deg"},
    {"kind":"number","label":"Relative permittivity (epsilon_r)","key":"epsR","min":1,"max":20,"step":0.1,"default":1},
    {"kind":"number","label":"Relative permeability (mu_r)","key":"muR","min":1,"max":20,"step":0.1,"default":1},
  ],
  "/momentum-collision-1d": [
    {"kind":"number","label":"Mass A","key":"mom1d-mass-a","min":0.5,"max":20,"step":0.1,"default":4,"units":"kg"},
    {"kind":"number","label":"Initial velocity A","key":"mom1d-vel-a","min":-10,"max":10,"step":0.1,"default":4,"units":"m/s"},
    {"kind":"number","label":"Mass B","key":"mom1d-mass-b","min":0.5,"max":20,"step":0.1,"default":6,"units":"kg"},
    {"kind":"number","label":"Initial velocity B","key":"mom1d-vel-b","min":-10,"max":10,"step":0.1,"default":-2,"units":"m/s"},
  ],
  "/oscillations-standing-waves": [
    {"kind":"number","label":"String length (L)","key":"L","min":1,"max":250,"step":0.1,"default":6,"units":"m"},
    {"kind":"number","label":"Wave speed (v)","key":"v","min":1,"max":100,"step":1,"default":24,"units":"m/s"},
    {"kind":"number","label":"Driving frequency (f)","key":"f","min":0.1,"max":20,"step":0.05,"default":2,"units":"Hz"},
    {"kind":"number","label":"Drive amplitude","key":"amp","min":0.1,"max":5,"step":0.1,"default":1.5,"units":"m"},
  ],
  "/oscillations-vertical-spring": [
    {"kind":"number","label":"Spring constant (k)","key":"k","min":1,"max":500,"step":1,"default":40,"units":"N/m"},
    {"kind":"number","label":"Mass","key":"m","min":0.1,"max":100,"step":0.1,"default":2,"units":"kg"},
    {"kind":"number","label":"Gravity (g)","key":"g","min":0.1,"max":25,"step":0.1,"default":9.81,"units":"m/s²"},
    {"kind":"number","label":"Initial displacement (y₀)","key":"y0","min":-5,"max":5,"step":0.05,"default":0.8,"units":"m"},
  ],
  "/oscillations-wave-generator": [
    {"kind":"number","label":"Amplitude (A)","key":"amp","min":0.1,"max":5,"step":0.1,"default":1.2,"units":"m"},
    {"kind":"number","label":"Frequency (f)","key":"freq","min":0.1,"max":10,"step":0.1,"default":2,"units":"Hz"},
    {"kind":"number","label":"Wave speed (v)","key":"speed","min":1,"max":50,"step":0.5,"default":10,"units":"m/s"},
    {"kind":"number","label":"Probe position (time graph)","key":"probe","min":0,"max":14,"step":0.1,"default":5,"units":"m"},
  ],
  "/pulley-system": [
    {"kind":"number","label":"Mass 1 (left side)","key":"mass-1-left-side","min":0.5,"max":20,"step":0.1,"default":5,"units":"kg"},
    {"kind":"number","label":"Mass 2 (right side)","key":"mass-2-right-side","min":0.5,"max":20,"step":0.1,"default":8,"units":"kg"},
  ],
  "/rc-circuit": [
    {"kind":"number","label":"Resistance R","key":"resistance-r","min":100,"max":10000,"step":50,"default":2200,"units":"Ω"},
    {"kind":"number","label":"Capacitance C","key":"capacitance-c","min":50,"max":2200,"step":10,"default":470,"units":"μF"},
    {"kind":"number","label":"Source voltage","key":"source-voltage","min":1,"max":12,"step":0.1,"default":9,"units":"V"},
    {"kind":"number","label":"Initial capacitor charge","key":"initial-capacitor-charge","min":0,"max":5000,"step":25,"default":0,"units":"μC"},
  ],
  "/rotational-taut-string": [
    {"kind":"number","label":"Mass","key":"m","min":0.5,"max":20,"step":0.1,"default":2,"units":"kg"},
    {"kind":"number","label":"String length / radius","key":"r","min":1,"max":10,"step":0.1,"default":4,"units":"m"},
    {"kind":"number","label":"Initial angular velocity (ω₀)","key":"omega0","min":0,"max":10,"step":0.1,"default":2.5,"units":"rad/s"},
    {"kind":"number","label":"Gravity strength (g)","key":"g","min":0,"max":25,"step":0.1,"default":9.81,"units":"m/s²"},
  ],
  "/spring-energy": [
    {"kind":"number","label":"Mass (m)","key":"mass-m","min":0.5,"max":20,"step":0.5,"default":5,"units":"kg"},
    {"kind":"number","label":"Spring constant (k)","key":"spring-constant-k","min":1,"max":50,"step":1,"default":10,"units":"N/m"},
    {"kind":"number","label":"Initial displacement (x₀)","key":"initial-displacement-x","min":-5,"max":5,"step":0.1,"default":2,"units":"m"},
  ],
  "/spring-force": [
    {"kind":"number","label":"Mass (m)","key":"mass-m","min":1,"max":12,"step":0.5,"default":5,"units":"kg"},
    {"kind":"number","label":"Spring constant (k)","key":"spring-constant-k","min":1,"max":50,"step":1,"default":10,"units":"N/m"},
    {"kind":"number","label":"Displacement (x)","key":"displacement-x","min":-6,"max":6,"step":0.1,"default":0,"units":"m"},
  ],
  
};
